# Generated by Django 6.0 on 2025-12-18 14:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0012_remove_academic_year_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(help_text='e.g., Semester 1, Trimester 1, Term 1', max_length=100)),
                ('academic_year', models.CharField(help_text='Format: YYYY/YYYY (e.g., 2024/2025)', max_length=20)),
                ('semester_number', models.IntegerField(help_text='Semester number (1, 2, 3, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently active term')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='education.college')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['-academic_year', 'semester_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='education.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.term')),
            ],
            options={
                'db_table': 'student_invoices',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('registration', 'Registration Fee'), ('library', 'Library Fee'), ('examination', 'Examination Fee'), ('activity', 'Activity Fee'), ('medical', 'Medical Fee'), ('other', 'Other')], default='tuition', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='education.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='education.collegecourse')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.term')),
            ],
            options={
                'db_table': 'fee_structures',
                'ordering': ['course', 'term', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='education.college')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['department_name'],
                'unique_together': {('college', 'department_name')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'MPesa'), ('bank_transfer', 'Bank Transfer'), ('bank_deposit', 'Bank Deposit'), ('cheque', 'Cheque'), ('scholarship', 'Scholarship'), ('other', 'Other')], max_length=50)),
                ('transaction_code', models.CharField(blank=True, help_text='MPesa code, cheque number, bank reference, etc.', max_length=100, null=True)),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.student')),
                ('invoice', models.ForeignKey(blank=True, help_text='Leave empty for advance payments or overpayments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.studentinvoice')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date_paid'],
                'indexes': [models.Index(fields=['student', 'date_paid'], name='payments_student_849369_idx'), models.Index(fields=['invoice'], name='payments_invoice_9dd568_idx'), models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx'), models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['college', 'academic_year'], name='terms_college_0e1a23_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year'], name='terms_academi_4bab35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('college', 'term_name', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['student', 'status'], name='student_inv_student_3ac086_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['term'], name='student_inv_term_id_9926a6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['status'], name='student_inv_status_72b256_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['invoice_number'], name='student_inv_invoice_0d6921_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinvoice',
            unique_together={('student', 'term')},
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['college', 'course'], name='fee_structu_college_529004_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['term'], name='fee_structu_term_id_6f75ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('course', 'term', 'fee_type')},
        ),
    ]
