# Generated by Django 6.0 on 2025-12-19 08:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('education', '0016_add_course_code_field'),
    ]

    operations = [
        # First, remove the old unique constraint and index
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fee_structu_term_id_6f75ee_idx',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),  # Remove old constraint first
        ),
        
        # Add all new fields before creating new constraints
        migrations.AddField(
            model_name='feestructure',
            name='semester_number',
            field=models.IntegerField(blank=True, help_text='Semester position in course (1, 2, 3... up to total semesters)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Version number of this fee structure'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when this version becomes active'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Date when this version expires (null = current version)', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_current_version',
            field=models.BooleanField(default=True, help_text='Whether this is the current active version'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='replaced_by_version',
            field=models.ForeignKey(blank=True, help_text='New version that replaced this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='accounts.feestructure'),
        ),
        
        # Add StudentInvoice fields
        migrations.AddField(
            model_name='studentinvoice',
            name='fee_breakdown_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Complete fee breakdown at invoice time'),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='fee_structure_version_id',
            field=models.IntegerField(blank=True, help_text='ID of fee structure version used', null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='is_amount_locked',
            field=models.BooleanField(default=True, help_text='Whether invoice amount is locked (prevents retroactive changes)'),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When invoice amount was locked', null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='original_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original fee amount before discounts', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='semester_number',
            field=models.IntegerField(blank=True, help_text='Semester number in course when invoice was generated', null=True),
        ),
        
        # Now create new constraints and indexes
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('course', 'semester_number', 'fee_type', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['course', 'semester_number'], name='fee_structu_course__785378_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_current_version', 'effective_from'], name='fee_structu_is_curr_17b921_idx'),
        ),
        
        # Update model options
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['course', 'semester_number', 'fee_type', 'version_number']},
        ),
        
        # Alter existing fields
        migrations.AlterField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this fee structure is active'),
        ),
        migrations.AlterField(
            model_name='studentinvoice',
            name='term',
            field=models.ForeignKey(help_text='Academic term for tracking purposes', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.term'),
        ),
        
        # Finally, remove the term field from FeeStructure
        migrations.RemoveField(
            model_name='feestructure',
            name='term',
        ),
    ]
