# Generated by Django 6.0 on 2025-12-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_semester_numbers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinvoice',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='studentinvoice',
            name='student_inv_student_3ac086_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentinvoice',
            name='student_inv_term_id_9926a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentinvoice',
            name='student_inv_status_72b256_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentinvoice',
            name='student_inv_invoice_0d6921_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_invoice_9dd568_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='StudentInvoice',
        ),
    ]
