# Generated by Django 6.0 on 2025-12-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentinvoice_unique_together_and_more'),
        ('education', '0017_student_is_sponsored_student_sponsorship_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2024/2025)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester_number',
            field=models.IntegerField(blank=True, help_text='Semester number this payment is for (optional)', null=True),
        ),
        migrations.CreateModel(
            name='AccountsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_enabled', models.BooleanField(default=False, help_text='Enable school sponsorship system')),
                ('sponsorship_default_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', help_text='Default discount type for sponsored students', max_length=20)),
                ('sponsorship_default_discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Default discount value (percentage 0-100 or fixed amount in KES)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_settings', to='education.college')),
            ],
            options={
                'verbose_name': 'Accounts Settings',
                'verbose_name_plural': 'Accounts Settings',
                'db_table': 'accounts_settings',
            },
        ),
    ]
