# Generated by Django 6.0 on 2025-12-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_invoice_automatic_generation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_invoice_9dd568_idx',
            old_name='payments_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvoice',
            new_name='student_inv_student_25f40d_idx',
            old_name='student_inv_student_sem_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvoice',
            new_name='student_inv_status_72b256_idx',
            old_name='student_inv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvoice',
            new_name='student_inv_invoice_0d6921_idx',
            old_name='student_inv_invoice_num_idx',
        ),
        migrations.RenameIndex(
            model_name='studentinvoice',
            new_name='student_inv_academi_e873bc_idx',
            old_name='student_inv_academic_year_idx',
        ),
    ]
