# Generated by Django 6.0 on 2025-12-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_payments_invoice_idx_payments_invoice_9dd568_idx_and_more'),
        ('education', '0018_student_has_ream_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('paybill', 'Paybill Number'), ('till', 'Till Number')], default='paybill', help_text='Select Paybill or Till Number', max_length=10)),
                ('paybill_number', models.CharField(blank=True, help_text='Paybill Number (e.g., 123456)', max_length=20, null=True)),
                ('till_number', models.CharField(blank=True, help_text='Till Number (e.g., 123456)', max_length=20, null=True)),
                ('consumer_key', models.TextField(blank=True, help_text='Daraja API Consumer Key from Safaricom Developer Portal', null=True)),
                ('consumer_secret', models.TextField(blank=True, help_text='Daraja API Consumer Secret from Safaricom Developer Portal', null=True)),
                ('passkey', models.TextField(blank=True, help_text='Daraja API Passkey (Lipa na M-Pesa Online Passkey)', null=True)),
                ('shortcode', models.CharField(blank=True, help_text='Business Shortcode (same as Paybill/Till number)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Enable M-Pesa payments for this college')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use Daraja Sandbox for testing (disable for production)')),
                ('callback_url', models.URLField(blank=True, help_text='Callback URL for payment confirmations (auto-generated if blank)', null=True)),
                ('account_reference', models.CharField(blank=True, help_text="Account Reference prefix (e.g., 'FEE' - will be appended with student admission number)", max_length=100, null=True)),
                ('transaction_description', models.CharField(default='Fee Payment', help_text='Transaction description shown in M-Pesa prompt', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daraja_settings', to='education.college')),
            ],
            options={
                'verbose_name': 'Daraja M-Pesa Settings',
                'verbose_name_plural': 'Daraja M-Pesa Settings',
                'db_table': 'daraja_settings',
            },
        ),
    ]
