# Generated by Django 6.0 on 2025-12-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_darajasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajasettings',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account Name (e.g., Cambridge College)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank Branch Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name (e.g., Equity Bank, KCB, Co-operative Bank)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC Code (for international transfers)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_transfer_instructions',
            field=models.TextField(blank=True, help_text="Additional instructions for bank transfers (e.g., 'Use admission number as reference')", null=True),
        ),
        migrations.AddField(
            model_name='darajasettings',
            name='bank_transfers_enabled',
            field=models.BooleanField(default=False, help_text='Enable direct bank transfer payments'),
        ),
    ]
