# Generated by Django 6.0 on 2025-12-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_darajasettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='term',
            name='terms_college_0e1a23_idx',
        ),
        migrations.RemoveIndex(
            model_name='term',
            name='terms_academi_4bab35_idx',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
