# Generated by Django 6.0 on 2025-12-24 12:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_term_unique_together_and_more'),
        ('education', '0022_college_max_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='darajasettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name (e.g., Equity Bank, KCB, Co-operative Bank) - Display only, not used in payment flow', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DailyExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('accounts_officer', 'Accounts Officer')], help_text='Role of person entering the expenditure', max_length=20)),
                ('description', models.TextField(help_text='Description of the expenditure')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expenditure amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when entry was created (auto-set, not editable)')),
                ('submitted', models.BooleanField(default=False, help_text='Whether this entry has been submitted (draft if False)')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Date and time when entry was submitted', null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenditures', to='education.college')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_expenditures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_expenditures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['college', 'created_at'], name='daily_expen_college_fb0b60_idx'), models.Index(fields=['college', 'submitted', 'created_at'], name='daily_expen_college_52dda5_idx'), models.Index(fields=['entered_by', 'submitted'], name='daily_expen_entered_6cb523_idx')],
            },
        ),
    ]
