# Generated by Django 6.0 on 2025-12-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_darajasettings_bank_name_dailyexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpenditure',
            name='role',
            field=models.CharField(blank=True, choices=[('principal', 'Principal'), ('accounts_officer', 'Accounts Officer')], help_text='Role of person entering the expenditure (auto-set)', max_length=20, null=True),
        ),
    ]
