# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_dailyexpenditure_role'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the fee item (e.g., Tuition Fee, Registration Fee)', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this fee item covers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fee Item',
                'verbose_name_plural': 'Fee Items',
                'db_table': 'fee_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_fee_structures', to='education.collegecourse')),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_fee_structures', to='accounts.feeitem')),
            ],
            options={
                'verbose_name': 'Course Fee Structure',
                'verbose_name_plural': 'Course Fee Structures',
                'db_table': 'course_fee_structures',
                'ordering': ['course', 'fee_item'],
                'unique_together': {('course', 'fee_item')},
            },
        ),
        migrations.AddIndex(
            model_name='coursefeestructure',
            index=models.Index(fields=['course'], name='course_fee_course_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeestructure',
            index=models.Index(fields=['fee_item'], name='course_fee_fee_item_idx'),
        ),
    ]

