# Generated by Django

from django.db import migrations, models
import django.core.validators


def set_default_semester(apps, schema_editor):
    """Set default semester_number to 1 for existing records"""
    CourseFeeStructure = apps.get_model('accounts', 'CourseFeeStructure')
    CourseFeeStructure.objects.filter(semester_number__isnull=True).update(semester_number=1)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_feeitem_coursefeestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeestructure',
            name='semester_number',
            field=models.IntegerField(null=True, blank=True, help_text='Semester position in course (1, 2, 3... up to total semesters)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(set_default_semester, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='coursefeestructure',
            name='semester_number',
            field=models.IntegerField(help_text='Semester position in course (1, 2, 3... up to total semesters)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='coursefeestructure',
            unique_together={('course', 'fee_item', 'semester_number')},
        ),
        migrations.RemoveIndex(
            model_name='coursefeestructure',
            name='course_fee_course_idx',
        ),
        migrations.RemoveIndex(
            model_name='coursefeestructure',
            name='course_fee_fee_item_idx',
        ),
        migrations.AddIndex(
            model_name='coursefeestructure',
            index=models.Index(fields=['course', 'semester_number'], name='course_fee_course_sem_idx'),
        ),
    ]

