# Generated by Django 5.1.1 on 2025-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_semester_to_course_fee_structure'),
        ('education', '0023_collegetimetable_file_alter_collegetimetable_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefeestructure',
            options={'ordering': ['course', 'semester_number', 'fee_item'], 'verbose_name': 'Course Fee Structure', 'verbose_name_plural': 'Course Fee Structures'},
        ),
        migrations.RenameIndex(
            model_name='coursefeestructure',
            new_name='course_fee__course__dc3990_idx',
            old_name='course_fee_course_sem_idx',
        ),
        migrations.AddIndex(
            model_name='coursefeestructure',
            index=models.Index(fields=['course'], name='course_fee__course__ec5127_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeestructure',
            index=models.Index(fields=['fee_item'], name='course_fee__fee_ite_44746e_idx'),
        ),
    ]
