# Generated by Django 5.1.1 on 2026-01-01 07:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0028_reporttemplatemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semester', 'Per Semester'), ('yearly', 'Yearly'), ('custom', 'Custom Days')], default='monthly', help_text='Payment period type', max_length=20)),
                ('validity_days', models.IntegerField(default=30, help_text='Number of days payment is valid (for custom period)', validators=[django.core.validators.MinValueValidator(1)])),
                ('paybill_number', models.CharField(help_text='Paybill number / shortcode', max_length=20)),
                ('account_reference_format', models.CharField(default='COLLEGE-{college_id}', help_text='Account reference format (use {college_id}, {college_name}, {branch_id})', max_length=100)),
                ('callback_url', models.URLField(blank=True, help_text='Callback URL for payment confirmations (auto-generated if blank)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Whether this payment config is active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='If this is a branch-specific config', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_payment_configs', to='education.college')),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='education.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College Payment Configuration',
                'verbose_name_plural': 'College Payment Configurations',
                'db_table': 'college_payment_configs',
            },
        ),
        migrations.CreateModel(
            name='CollegePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='M-Pesa receipt number', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for payment', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('valid_from', models.DateField(blank=True, help_text='Payment validity start date', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Payment validity end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch college if payment is for a branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_payments', to='education.college')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_payments', to='education.college')),
                ('config', models.ForeignKey(blank=True, help_text='Payment configuration used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='superadmin.collegepaymentconfig')),
            ],
            options={
                'verbose_name': 'College Payment',
                'verbose_name_plural': 'College Payments',
                'db_table': 'college_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collegepaymentconfig',
            index=models.Index(fields=['college', 'status'], name='college_pay_college_f29d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepaymentconfig',
            index=models.Index(fields=['branch', 'status'], name='college_pay_branch__bd2879_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['college', 'status'], name='college_pay_college_d63117_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['branch', 'status'], name='college_pay_branch__794885_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['merchant_request_id'], name='college_pay_merchan_2a8cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['checkout_request_id'], name='college_pay_checkou_a58eab_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['receipt_number'], name='college_pay_receipt_bc9e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='collegepayment',
            index=models.Index(fields=['payment_date'], name='college_pay_payment_9480c4_idx'),
        ),
    ]
