# Generated by Django 5.1.1 on 2026-01-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegepaymentconfig',
            name='paybill_number',
            field=models.CharField(blank=True, default='', help_text='Paybill number / shortcode', max_length=20),
        ),
    ]
