# Generated by Django 5.1.1 on 2025-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for student login', max_length=128),
        ),
    ]
