# Generated by Django 5.1.1 on 2025-12-05 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models, connection


def _check_column_exists(cursor, table_name, column_name):
    """Check if a column exists in a table"""
    db_backend = connection.vendor
    if db_backend == 'sqlite':
        cursor.execute("PRAGMA table_info({})".format(table_name))
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns
    else:
        # MySQL/MariaDB
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = %s
            AND column_name = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def _add_created_at_if_not_exists(apps, schema_editor):
    """Add created_at column only if it doesn't exist"""
    db_backend = connection.vendor
    with connection.cursor() as cursor:
        if not _check_column_exists(cursor, 'college_course_units', 'created_at'):
            if db_backend == 'sqlite':
                cursor.execute("""
                    ALTER TABLE college_course_units
                    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                """)
            else:
                # MySQL
                cursor.execute("""
                    ALTER TABLE college_course_units
                    ADD COLUMN created_at DATETIME NULL
                """)
                # Set created_at to current timestamp for existing records
                cursor.execute("UPDATE college_course_units SET created_at = NOW() WHERE created_at IS NULL;")
                # Make it NOT NULL after setting values
                cursor.execute("ALTER TABLE college_course_units MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP")
        else:
            # Column exists, just update NULL values if any
            if db_backend != 'sqlite':
                cursor.execute("UPDATE college_course_units SET created_at = NOW() WHERE created_at IS NULL;")


def _add_updated_at_if_not_exists(apps, schema_editor):
    """Add updated_at column only if it doesn't exist"""
    db_backend = connection.vendor
    with connection.cursor() as cursor:
        if not _check_column_exists(cursor, 'college_course_units', 'updated_at'):
            if db_backend == 'sqlite':
                # SQLite doesn't support ON UPDATE, so just use DEFAULT
                cursor.execute("""
                    ALTER TABLE college_course_units
                    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                """)
            else:
                # MySQL
                cursor.execute("""
                    ALTER TABLE college_course_units
                    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                """)


def _update_unique_constraint(schema_editor):
    """Drop old unique constraint and create new one manually to avoid FK index conflicts"""
    db_backend = connection.vendor
    with connection.cursor() as cursor:
        if db_backend == 'sqlite':
            # SQLite: Check if unique constraint exists and create if needed
            # SQLite doesn't support DROP INDEX for unique constraints easily, so we'll just try to create it
            try:
                cursor.execute("""
                    CREATE UNIQUE INDEX IF NOT EXISTS college_course_units_course_unit_year_sem_uniq
                    ON college_course_units(course_id, unit_id, year_of_study, semester)
                """)
            except Exception as e:
                # If it already exists, that's fine
                if 'already exists' not in str(e).lower() and 'duplicate' not in str(e).lower():
                    raise
        else:
            # MySQL: Drop old unique constraint if it exists
            cursor.execute("""
                SELECT index_name FROM information_schema.statistics
                WHERE table_schema = DATABASE()
                AND table_name = 'college_course_units'
                AND index_name LIKE '%course_id%unit_id%'
                AND non_unique = 0
            """)
            old_indexes = [row[0] for row in cursor.fetchall()]
            
            for index_name in old_indexes:
                if 'uniq' in index_name.lower():
                    try:
                        cursor.execute(f"ALTER TABLE college_course_units DROP INDEX `{index_name}`")
                    except Exception:
                        pass
            
            # Create new unique constraint manually (bypassing Django's FK index creation)
            try:
                cursor.execute("""
                    ALTER TABLE college_course_units
                    ADD UNIQUE KEY college_course_units_course_unit_year_sem_uniq
                    (course_id, unit_id, year_of_study, semester)
                """)
            except Exception as e:
                # If it already exists, that's fine
                if 'Duplicate key' not in str(e) and 'already exists' not in str(e):
                    raise


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_student_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegecourseunit',
            options={'ordering': ['course', 'year_of_study', 'semester', 'unit__code']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    # Add created_at column only if it doesn't exist
                    code=_add_created_at_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    # Add updated_at column only if it doesn't exist
                    code=_add_updated_at_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                # Update Django's state to reflect the new fields
                migrations.AddField(
                    model_name='collegecourseunit',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, null=True),
                ),
                migrations.AlterField(
                    model_name='collegecourseunit',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AddField(
                    model_name='collegecourseunit',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='collegecourseunit',
            name='year_of_study',
            field=models.IntegerField(default=1, help_text='Year of study (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(blank=True, help_text='Date of graduation (if graduated)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('deferred', 'Deferred')], default='active', help_text='Student status', max_length=20),
        ),
        migrations.AlterField(
            model_name='collegecourseunit',
            name='semester',
            field=models.IntegerField(help_text='Semester (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.RunPython(
            # Remove old unique constraint and create new one manually
            code=lambda apps, schema_editor: _update_unique_constraint(schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
    ]

