# Generated by Django 5.1.1 on 2025-12-05 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models, connection


def _ensure_unique_constraint(apps, schema_editor):
    """Ensure the unique constraint exists on (course, unit, year_of_study, semester)"""
    db_backend = connection.vendor
    with connection.cursor() as cursor:
        if db_backend == 'sqlite':
            # SQLite: Check if index exists by querying sqlite_master
            cursor.execute("""
                SELECT name FROM sqlite_master
                WHERE type='index' AND name='college_course_units_course_unit_year_sem_uniq'
            """)
            constraint_exists = cursor.fetchone() is not None
            
            if not constraint_exists:
                # Try to create the constraint
                try:
                    cursor.execute("""
                        CREATE UNIQUE INDEX IF NOT EXISTS college_course_units_course_unit_year_sem_uniq
                        ON college_course_units(course_id, unit_id, year_of_study, semester)
                    """)
                except Exception as e:
                    # If it already exists or fails, that's okay - migration 0003 might have created it
                    if 'already exists' not in str(e).lower() and 'duplicate' not in str(e).lower():
                        print(f"Note: Could not create unique constraint (may already exist): {e}")
        else:
            # MySQL: Check if the constraint already exists
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.table_constraints
                WHERE table_schema = DATABASE()
                AND table_name = 'college_course_units'
                AND constraint_name = 'college_course_units_course_unit_year_sem_uniq'
                AND constraint_type = 'UNIQUE'
            """)
            constraint_exists = cursor.fetchone()[0] > 0
            
            if not constraint_exists:
                # Try to create the constraint
                try:
                    cursor.execute("""
                        ALTER TABLE college_course_units
                        ADD UNIQUE KEY college_course_units_course_unit_year_sem_uniq
                        (course_id, unit_id, year_of_study, semester)
                    """)
                except Exception as e:
                    # If it already exists or fails, that's okay - migration 0003 might have created it
                    if 'Duplicate key' not in str(e) and 'already exists' not in str(e):
                        print(f"Note: Could not create unique constraint (may already exist): {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_collegecourseunit_options_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle constraint change safely
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # The constraint was already handled in migration 0003, so we just ensure it exists
                migrations.RunPython(
                    code=_ensure_unique_constraint,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                # Update Django's state to reflect the new unique_together
                migrations.AlterUniqueTogether(
                    name='collegecourseunit',
                    unique_together=set(),
                ),
                migrations.AlterField(
                    model_name='collegecourseunit',
                    name='course',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='education.collegecourse'),
                ),
                migrations.AlterField(
                    model_name='collegecourseunit',
                    name='unit',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='education.collegeunit'),
                ),
                migrations.AlterField(
                    model_name='collegecourseunit',
                    name='year_of_study',
                    field=models.IntegerField(help_text='Year of study (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
                ),
                migrations.AlterUniqueTogether(
                    name='collegecourseunit',
                    unique_together={('course', 'unit', 'year_of_study', 'semester')},
                ),
            ],
        ),
    ]
