# Generated by Django 5.1.1 on 2025-12-05 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_collegecourseunit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourseunit',
            name='semester',
            field=models.IntegerField(help_text='Semester (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='collegeunit',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')]),
        ),
        migrations.AlterField(
            model_name='globalcourseunit',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')]),
        ),
    ]
