# Generated by Django 5.1.1 on 2025-12-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_add_exam_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_type', models.CharField(choices=[('all_students', 'All Students'), ('all_lecturers', 'All Lecturers'), ('individual', 'Individual Users')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='education.college')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('targeted_students', models.ManyToManyField(blank=True, related_name='announcements', to='education.student')),
                ('targeted_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['college', 'target_type'], name='announcemen_college_905803_idx'), models.Index(fields=['college', 'is_active'], name='announcemen_college_2ce9c3_idx'), models.Index(fields=['college', 'created_at'], name='announcemen_college_296786_idx'), models.Index(fields=['is_active'], name='announcemen_is_acti_8058e7_idx')],
            },
        ),
    ]
