# Generated by Django 5.1.1 on 2025-12-05 15:35

import django.core.validators
import django.db.models.deletion
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload timetable image (JPG, PNG, GIF, WebP)', upload_to=education.models.timetable_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive timetables are hidden from students')),
                ('academic_year', models.CharField(blank=True, help_text='e.g., 2024/2025', max_length=20, null=True)),
                ('semester', models.IntegerField(blank=True, help_text='Semester 1, 2, or 3', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='education.college')),
                ('course', models.ForeignKey(blank=True, help_text='Leave empty for general timetable applicable to all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='education.collegecourse')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'college_timetables',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['college', 'is_active'], name='college_tim_college_0efb5d_idx'), models.Index(fields=['college', 'course'], name='college_tim_college_9cfe35_idx'), models.Index(fields=['academic_year', 'semester'], name='college_tim_academi_0416d8_idx')],
                'unique_together': {('college', 'course', 'academic_year', 'semester')},
            },
        ),
    ]
