# Generated by Django 5.1.1 on 2025-12-05 21:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_add_college_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='current_academic_year',
            field=models.CharField(blank=True, help_text='Current academic year (e.g., 2024/2025)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='current_semester',
            field=models.IntegerField(blank=True, help_text='Current active semester (1-3)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='college',
            name='nominal_roll_signin_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable semester nominal roll sign-in for students'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, help_text='Current semester (1-3)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='student',
            name='last_signin_academic_year',
            field=models.CharField(blank=True, help_text='Last sign-in academic year', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_signin_date',
            field=models.DateTimeField(blank=True, help_text='Last semester sign-in timestamp', null=True),
        ),
        migrations.CreateModel(
            name='StudentSemesterSignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=20)),
                ('semester', models.IntegerField(help_text='Semester (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('signed_in_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when student signed in')),
                ('year_of_study_at_signin', models.IntegerField(help_text='Year of study when signed in', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('semester_of_study_at_signin', models.IntegerField(help_text='Semester when signed in', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('next_year_of_study', models.IntegerField(help_text='Year of study after sign-in', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('next_semester', models.IntegerField(help_text='Semester after sign-in', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('is_processed', models.BooleanField(default=False, help_text="Whether student's year/semester was updated")),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date and time when sign-in was processed', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_signins', to='education.student')),
            ],
            options={
                'db_table': 'student_semester_signins',
                'ordering': ['-signed_in_at'],
                'indexes': [models.Index(fields=['student', 'academic_year', 'semester'], name='student_sem_student_76fc61_idx'), models.Index(fields=['academic_year', 'semester'], name='student_sem_academi_79dcb4_idx'), models.Index(fields=['signed_in_at'], name='student_sem_signed__a7d73e_idx')],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
