# Generated by Django 5.1.1 on 2025-12-06 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_college_current_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='grading_criteria',
            field=models.JSONField(blank=True, default=dict, help_text='Grading system configuration (weights, thresholds, etc.)'),
        ),
        migrations.AddField(
            model_name='college',
            name='semesters_per_year',
            field=models.IntegerField(default=2, help_text='Number of semesters per academic year (typically 2, 3, or 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='college',
            name='current_semester',
            field=models.IntegerField(blank=True, help_text='Current active semester', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='collegecourseunit',
            name='semester',
            field=models.IntegerField(help_text="Semester (validated against college's semesters_per_year)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='collegetimetable',
            name='semester',
            field=models.IntegerField(blank=True, help_text="Semester (validated against college's semesters_per_year)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.IntegerField(blank=True, help_text="Current semester (validated against college's semesters_per_year)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='studentsemestersignin',
            name='next_semester',
            field=models.IntegerField(help_text="Semester after sign-in (validated against college's semesters_per_year)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='studentsemestersignin',
            name='semester',
            field=models.IntegerField(help_text="Semester (validated against college's semesters_per_year)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='studentsemestersignin',
            name='semester_of_study_at_signin',
            field=models.IntegerField(help_text="Semester when signed in (validated against college's semesters_per_year)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
