# Generated by Django 5.1.1 on 2025-12-06 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_college_grading_criteria_college_semesters_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalcourseunit',
            name='semester',
        ),
        migrations.AlterField(
            model_name='collegeunit',
            name='semester',
            field=models.IntegerField(help_text="Semester (validated against college's semesters_per_year)", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
