# Generated by Django 5.1.1 on 2025-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_remove_globalcourseunit_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(help_text='Academic year in format YYYY/YYYY (e.g., 2024/2025)', max_length=20),
        ),
    ]
