# Generated by Django 6.0 on 2025-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_remove_academic_year_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director/Owner'), ('principal', 'Principal'), ('registrar', 'Registrar'), ('accounts_officer', 'Accounts Officer'), ('lecturer', 'Lecturer'), ('college_admin', 'College Admin')], default='lecturer', max_length=20),
        ),
    ]
