# Generated by Django 6.0 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director/Owner'), ('principal', 'Principal'), ('registrar', 'Registrar'), ('accounts_officer', 'Accounts Officer'), ('reception', 'Reception'), ('lecturer', 'Lecturer'), ('college_admin', 'College Admin')], default='lecturer', max_length=20),
        ),
    ]

