# Generated by Django migration

from django.db import migrations, models


def populate_course_codes(apps, schema_editor):
    """Populate course codes for existing courses"""
    CollegeCourse = apps.get_model('education', 'CollegeCourse')
    for course in CollegeCourse.objects.all():
        if not course.code:
            # Generate a code from course ID if not set
            course.code = f'COURSE{course.id}'
            course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_add_reception_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecourse',
            name='code',
            field=models.CharField(default='', help_text='Course code (e.g., CS101)', max_length=50),
            preserve_default=False,
        ),
        migrations.RunPython(populate_course_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='collegecourse',
            name='code',
            field=models.CharField(help_text='Course code (e.g., CS101)', max_length=50),
        ),
    ]

