# Generated by Django 6.0 on 2025-12-19 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_add_course_code_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_sponsored',
            field=models.BooleanField(default=False, help_text='Whether student is school-sponsored'),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_approved_at',
            field=models.DateTimeField(blank=True, help_text='When sponsorship was approved', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved sponsorship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], help_text='Discount type for this student', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sponsorship_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount value (percentage 0-100 or fixed amount in KES)', max_digits=10, null=True),
        ),
    ]
