# Generated by Django 6.0 on 2025-12-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_student_is_sponsored_student_sponsorship_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_ream_paper',
            field=models.BooleanField(default=False, help_text='Whether student has submitted ream paper'),
        ),
    ]
