# Generated by Django 6.0 on 2025-12-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('education', '0019_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='parent_college',
            field=models.ForeignKey(blank=True, help_text='Parent college if this is a branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_colleges', to='education.college'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['registration_status'], name='colleges_registr_206c31_idx'),
        ),
        migrations.AddIndex(
            model_name='college',
            index=models.Index(fields=['email'], name='colleges_email_b03c84_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['college', 'name'], name='college_cou_college_6dbf41_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['college', 'code'], name='college_cou_college_94d9be_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourse',
            index=models.Index(fields=['college', 'global_course'], name='college_cou_college_787fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourseunit',
            index=models.Index(fields=['college', 'course', 'year_of_study', 'semester'], name='college_cou_college_7df9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourseunit',
            index=models.Index(fields=['unit', 'college'], name='college_cou_unit_id_7fd02a_idx'),
        ),
        migrations.AddIndex(
            model_name='collegecourseunit',
            index=models.Index(fields=['course', 'semester'], name='college_cou_course__edd784_idx'),
        ),
        migrations.AddIndex(
            model_name='collegeunit',
            index=models.Index(fields=['college', 'assigned_lecturer'], name='college_uni_college_04b7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='collegeunit',
            index=models.Index(fields=['college', 'semester'], name='college_uni_college_78825b_idx'),
        ),
        migrations.AddIndex(
            model_name='collegeunit',
            index=models.Index(fields=['college', 'code'], name='college_uni_college_f6fc27_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['college', 'role'], name='users_college_cc055e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['college', 'username'], name='users_college_9f705d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'academic_year', 'semester'], name='enrollments_student_db456a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['unit', 'academic_year'], name='enrollments_unit_id_75eea3_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_year', 'semester'], name='enrollments_academi_cfe552_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['exam_registered'], name='enrollments_exam_re_7d7d07_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'exam_registered'], name='enrollments_student_b4b7a0_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['entered_by', 'status'], name='results_entered_8b46a2_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['status'], name='results_status_85f0af_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['entered_at'], name='results_entered_6f96e6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'status'], name='students_college_a72fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'course', 'status'], name='students_college_a31792_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'full_name'], name='students_college_572cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'year_of_study'], name='students_college_854491_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'admission_number'], name='students_college_060823_idx'),
        ),
    ]
