# Generated by Django 6.0 on 2025-12-22 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_college_parent_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistration',
            name='number_of_students',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='number_of_teachers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='schoolregistration',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('owner', 'Owner'), ('principal', 'Principal'), ('administrator', 'Administrator')], max_length=20),
        ),
    ]
