# Generated by Django 6.0 on 2025-12-23 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_update_school_registration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='max_branches',
            field=models.IntegerField(default=5, help_text='Maximum number of branches this college can create', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
