# Generated by Django 5.1.1 on 2025-12-30 02:00

import education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_college_max_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetimetable',
            name='file',
            field=models.FileField(blank=True, help_text='Upload timetable file (PDF, JPG, PNG, GIF, WebP)', null=True, upload_to=education.models.timetable_upload_path),
        ),
        migrations.AlterField(
            model_name='collegetimetable',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload timetable image (JPG, PNG, GIF, WebP)', null=True, upload_to=education.models.timetable_upload_path),
        ),
    ]
