# Generated by Django 5.1.1 on 2025-12-31 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_collegetimetable_file_alter_collegetimetable_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('report_type', models.CharField(choices=[('transcript', 'Transcript'), ('certificate', 'Certificate'), ('result_slip', 'Result Slip'), ('custom', 'Custom Report')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('canvas_width', models.IntegerField(default=800, help_text='Canvas width in pixels')),
                ('canvas_height', models.IntegerField(default=1000, help_text='Canvas height in pixels')),
                ('elements', models.JSONField(default=list, help_text='Array of report elements (text boxes, images, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='education.college')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['college', 'is_active'], name='report_temp_college_39ba53_idx'), models.Index(fields=['college', 'report_type'], name='report_temp_college_02baab_idx')],
            },
        ),
    ]
