# Generated by Django 5.1.1 on 2025-12-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4 (794 × 1123 px)'), ('A3', 'A3 (1123 × 1587 px)'), ('A5', 'A5 (559 × 794 px)'), ('Letter', 'Letter (816 × 1056 px)')], default='A4', help_text='Page size for the template', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='canvas_height',
            field=models.IntegerField(default=1123, help_text='Canvas height in pixels'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='canvas_width',
            field=models.IntegerField(default=794, help_text='Canvas width in pixels'),
        ),
    ]
