# Generated by Django 5.1.1 on 2025-12-31 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_reporttemplate_page_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template_mapping', to='education.college')),
                ('exam_card_template', models.ForeignKey(blank=True, help_text='Template to use for Exam Card reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_card_mappings', to='education.reporttemplate')),
                ('fee_structure_template', models.ForeignKey(blank=True, help_text='Template to use for Fee Structure reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structure_mappings', to='education.reporttemplate')),
                ('transcript_template', models.ForeignKey(blank=True, help_text='Template to use for Transcript reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_mappings', to='education.reporttemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template Mapping',
                'verbose_name_plural': 'Report Template Mappings',
                'db_table': 'report_template_mappings',
            },
        ),
    ]
