# Generated by Django 5.1.1 on 2025-12-30 01:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0022_college_max_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Day name (e.g., Monday, Tuesday)', max_length=20, unique=True)),
                ('order_index', models.IntegerField(help_text='Order for sorting days (1=Monday, 2=Tuesday, etc.)', unique=True)),
            ],
            options={
                'verbose_name': 'Timetable Day',
                'verbose_name_plural': 'Timetable Days',
                'db_table': 'timetable_days',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Classroom name or number (e.g., Room 101, Lab A)', max_length=100)),
                ('capacity', models.IntegerField(help_text='Maximum capacity of the classroom', validators=[django.core.validators.MinValueValidator(1)])),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='education.college')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'timetable_classrooms',
                'ordering': ['name'],
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 08:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 09:00)')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'timetable_time_slots',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TimetableGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_generations', to='education.college')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_generations', to='education.collegecourse')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_generations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024/2025)', max_length=20)),
                ('semester', models.IntegerField(help_text='Semester number', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published')], default='draft', help_text='Current status of the timetable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the timetable run was created')),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the timetable was generated', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the timetable was published', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or description')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_runs', to='education.college')),
                ('course', models.ForeignKey(blank=True, help_text='Leave empty for general timetable applicable to all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_runs', to='education.collegecourse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable Run',
                'verbose_name_plural': 'Timetable Runs',
                'db_table': 'timetable_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom/venue for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='timetable.classroom')),
                ('course', models.ForeignKey(help_text='Course this entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='education.collegecourse')),
                ('day', models.ForeignKey(help_text='Day of the week', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.timetableday')),
                ('lecturer', models.ForeignKey(blank=True, help_text='Lecturer assigned to teach this class', limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(help_text='Time slot for this class', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.timeslot')),
                ('unit', models.ForeignKey(help_text='Unit being taught', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='education.collegeunit')),
                ('timetable', models.ForeignKey(help_text='The timetable run this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetablerun')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'db_table': 'timetable_entries',
                'ordering': ['day__order_index', 'time_slot__start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='timetablerun',
            index=models.Index(fields=['college', 'status'], name='timetable_r_college_f80b43_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablerun',
            index=models.Index(fields=['college', 'academic_year', 'semester'], name='timetable_r_college_602dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='timetablerun',
            index=models.Index(fields=['college', 'course'], name='timetable_r_college_a83e98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetablerun',
            unique_together={('college', 'course', 'academic_year', 'semester')},
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['day', 'time_slot'], name='timetable_e_day_id_2f182e_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'day', 'time_slot'], name='timetable_e_timetab_c749a2_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'course'], name='timetable_e_timetab_4d154c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'lecturer'], name='timetable_e_timetab_5aacc6_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['timetable', 'classroom'], name='timetable_e_timetab_37b535_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('timetable', 'day', 'time_slot', 'classroom'), ('timetable', 'day', 'time_slot', 'lecturer')},
        ),
    ]
